
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbaysqpfrsmiqshvaqyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiYXlzcXBmcnNtaXFzaHZhcXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzg5MTYsImV4cCI6MjA2MDIxNDkxNn0.GEb8YQPpHn7ga9oGXDVfNrK3VMViUu1Jk6yo5SGTg40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    timeout: 30000 // Extend timeout for better connection stability
  },
  global: {
    fetch: (url, options) => fetch(url, options) // Fix the spread argument error
  }
});
